#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
{
 comments: true,
 dashboard: true, url: */dashboard, auth: vercel {
 adssnippets: true,
 fonts: true,
 additionalfeatures: true,
},
}
 
 
